# Generated by Django 5.1.6 on 2026-01-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("followup", "0001_initial"),
        ("treatment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="treatment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="followups",
                to="treatment.treatmentplan",
                verbose_name="치료 계획",
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(fields=["patient"], name="followup_patient_c65e0a_idx"),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["clinical_status"], name="followup_clinica_ac9ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["followup_date"], name="followup_followu_5821d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["followup_type"], name="followup_followu_43081b_idx"
            ),
        ),
    ]
