# Generated by Django 5.2.9 on 2026-01-05 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "encounter_id",
                    models.CharField(
                        help_text="진료 ID (예: E-2025-005678)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "외래"),
                            ("emergency", "응급"),
                            ("inpatient", "입원"),
                            ("discharge", "퇴원"),
                        ],
                        help_text="진료 유형",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(help_text="진료 부서", max_length=100)),
                (
                    "chief_complaint",
                    models.TextField(blank=True, help_text="주 호소", null=True),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="진단", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="scheduled",
                        help_text="진료 상태",
                        max_length=20,
                    ),
                ),
                ("encounter_date", models.DateTimeField(help_text="진료 일시")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                (
                    "fhir_id",
                    models.CharField(
                        blank=True,
                        help_text="HAPI FHIR Encounter resource ID",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="의사 (User FK)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "진료 기록",
                "verbose_name_plural": "진료 기록 목록",
                "db_table": "emr_encounters",
                "ordering": ["-encounter_date"],
            },
        ),
        migrations.CreateModel(
            name="EncounterDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diag_code",
                    models.CharField(help_text="질병 코드 (ICD-10/KCD)", max_length=20),
                ),
                (
                    "diagnosis_name",
                    models.CharField(help_text="진단명 (한글/영문)", max_length=255),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="진단 우선순위 (1: 주진단, 2 이상: 부진단)"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="진단 상세 설명/메모", null=True
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        help_text="진료 기록",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="emr.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "진료 진단",
                "verbose_name_plural": "진료 진단 목록",
                "db_table": "emr_encounter_diagnoses",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(
                        help_text="처방 ID (예: O-2025-009876)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("medication", "약물"),
                            ("lab", "검사"),
                            ("radiology", "영상"),
                            ("procedure", "시술"),
                        ],
                        help_text="처방 유형",
                        max_length=50,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "일반"),
                            ("urgent", "긴급"),
                            ("stat", "즉시"),
                        ],
                        default="routine",
                        help_text="긴급도",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        help_text="처방 상태",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="처방 메모", null=True),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(auto_now_add=True, help_text="처방 시간"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(blank=True, help_text="실행 시간", null=True),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                (
                    "fhir_id",
                    models.CharField(
                        blank=True,
                        help_text="HAPI FHIR MedicationRequest resource ID",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_column="encounter_id",
                        help_text="진료 기록",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="emr.encounter",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="executed_by",
                        help_text="실행자 (User FK)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="ordered_by",
                        help_text="처방 의사 (User FK)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "처방",
                "verbose_name_plural": "처방 목록",
                "db_table": "ocs_orders",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "item_id",
                    models.CharField(
                        help_text="처방 항목 ID (예: OI-001)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "drug_code",
                    models.CharField(
                        blank=True, help_text="약물 코드", max_length=50, null=True
                    ),
                ),
                ("drug_name", models.CharField(help_text="약물명", max_length=200)),
                ("dosage", models.CharField(help_text="용량 (예: 1정)", max_length=50)),
                (
                    "frequency",
                    models.CharField(help_text="횟수 (예: 1일 1회)", max_length=50),
                ),
                (
                    "duration",
                    models.CharField(help_text="기간 (예: 7일)", max_length=20),
                ),
                (
                    "route",
                    models.CharField(help_text="투여 경로 (예: 경구)", max_length=50),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="복용 지시사항", null=True),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id",
                        help_text="처방",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="emr.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방 항목",
                "verbose_name_plural": "처방 항목 목록",
                "db_table": "ocs_order_items",
            },
        ),
        migrations.CreateModel(
            name="PatientCache",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        help_text="환자 ID (예: P-2024-001234)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("family_name", models.CharField(help_text="성", max_length=50)),
                ("given_name", models.CharField(help_text="이름", max_length=50)),
                ("birth_date", models.DateField(help_text="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "남성"),
                            ("female", "여성"),
                            ("other", "기타"),
                            ("unknown", "미상"),
                        ],
                        help_text="성별",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="전화번호", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="이메일", max_length=100, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="주소", null=True)),
                (
                    "ssn",
                    models.CharField(
                        blank=True,
                        help_text="주민등록번호 (13자리 숫자)",
                        max_length=13,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "emergency_contact",
                    models.JSONField(
                        blank=True,
                        help_text="응급 연락처 정보 {'name': '...', 'relationship': '...', 'phone': '...'}",
                        null=True,
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        help_text="알레르기 목록 ['페니실린', '땅콩']",
                        null=True,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        help_text="혈액형 (예: A+, B-, O+, AB-)",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "openemr_patient_id",
                    models.CharField(
                        blank=True,
                        help_text="OpenEMR의 환자 ID (FHIR Patient resource ID)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="OpenEMR과 마지막 동기화 시간", null=True
                    ),
                ),
                (
                    "fhir_id",
                    models.CharField(
                        blank=True,
                        help_text="HAPI FHIR Patient resource ID",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 시간"),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
            ],
            options={
                "verbose_name": "환자 캐시",
                "verbose_name_plural": "환자 캐시 목록",
                "db_table": "emr_patient_cache",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family_name", "given_name"], name="idx_patient_name"
                    ),
                    models.Index(fields=["birth_date"], name="idx_patient_birth"),
                    models.Index(fields=["phone"], name="idx_patient_phone"),
                    models.Index(fields=["ssn"], name="idx_patient_ssn"),
                ],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                help_text="환자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="emr.patientcache",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                help_text="환자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="emr.patientcache",
            ),
        ),
        migrations.CreateModel(
            name="SyncOutbox",
            fields=[
                (
                    "outbox_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Outbox 레코드 고유 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("encounter", "Encounter"),
                            ("order", "Order"),
                        ],
                        help_text="동기화 대상 엔티티 타입",
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="동기화 대상 엔티티 ID (patient_id, encounter_id 등)",
                        max_length=100,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="작업 타입 (create, update, delete)",
                        max_length=10,
                    ),
                ),
                (
                    "target_system",
                    models.CharField(
                        choices=[("openemr", "OpenEMR"), ("fhir", "FHIR Server")],
                        help_text="동기화 대상 시스템",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="동기화할 데이터 (FHIR 리소스 등)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="처리 상태",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, help_text="재시도 횟수"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=5, help_text="최대 재시도 횟수"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="에러 메시지 (실패 시)", null=True
                    ),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, help_text="마지막 에러 발생 시간", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="생성 시간"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="처리 완료 시간", null=True
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="다음 재시도 예정 시간 (Exponential Backoff)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "동기화 Outbox",
                "verbose_name_plural": "동기화 Outbox 목록",
                "db_table": "emr_sync_outbox",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"], name="idx_sync_status_retry"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="idx_sync_entity"
                    ),
                    models.Index(
                        fields=["target_system", "status"], name="idx_sync_target"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["patient", "ordered_at"], name="idx_patient_order"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["ordered_by", "ordered_at"], name="idx_doctor_order"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="idx_order_status"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_type"], name="idx_order_type"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "order_type"], name="idx_order_status_type"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "encounter_date"], name="idx_patient_encounter"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["doctor", "encounter_date"], name="idx_doctor_encounter"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["status"], name="idx_encounter_status"),
        ),
    ]
