# Generated by Django 5.1.6 on 2026-01-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0002_status_snake_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="scheduled_time",
            field=models.TimeField(blank=True, null=True, verbose_name="예약 시간"),
        ),
    ]
