# Generated by Django 5.1.6 on 2026-01-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0003_add_scheduled_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="chief_complaint",
            field=models.TextField(
                blank=True,
                default="",
                help_text="환자가 호소하는 주요 증상",
                verbose_name="주 호소",
            ),
        ),
    ]
