# Generated by Django 5.1.6 on 2026-01-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0004_chief_complaint_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="assessment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="진단명, 감별진단",
                verbose_name="평가 (A)",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="objective",
            field=models.TextField(
                blank=True,
                default="",
                help_text="신체검사, 검사결과, 활력징후",
                verbose_name="객관적 소견 (O)",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="plan",
            field=models.TextField(
                blank=True,
                default="",
                help_text="치료계획, 처방, 추적관찰",
                verbose_name="계획 (P)",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="subjective",
            field=models.TextField(
                blank=True,
                default="",
                help_text="환자가 호소하는 증상, 병력",
                verbose_name="주관적 소견 (S)",
            ),
        ),
    ]
