# Generated by Django 5.2.9 on 2026-01-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTestMaster",
            fields=[
                (
                    "test_code",
                    models.CharField(
                        help_text="검사 코드 (LOINC/자체코드)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_name", models.CharField(help_text="검사명", max_length=255)),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        help_text="검체 유형 (예: Blood, Urine)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, help_text="검사 방법", max_length=100, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="검사 단위 (예: mg/dL, g/L)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True,
                        help_text="참고치 범위 (예: 70-110)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="사용 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "검사 마스터",
                "verbose_name_plural": "검사 마스터 목록",
                "db_table": "lis_lab_test_master",
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "result_id",
                    models.CharField(
                        help_text="결과 ID (예: LR-2025-000001)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_value",
                    models.CharField(
                        help_text="검사 결과값 (수치 또는 텍스트)", max_length=100
                    ),
                ),
                (
                    "result_unit",
                    models.CharField(
                        blank=True, help_text="결과 단위", max_length=50, null=True
                    ),
                ),
                (
                    "result_details",
                    models.JSONField(
                        blank=True, help_text="상세 결과 데이터 (JSON)", null=True
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, help_text="이상치 여부"),
                ),
                (
                    "abnormal_flag",
                    models.CharField(
                        blank=True,
                        help_text="이상치 플래그 (H: High, L: Low, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(auto_now_add=True, help_text="보고 일시"),
                ),
                (
                    "reported_by",
                    models.CharField(help_text="보고자 user_id", max_length=36),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="낙관적 락을 위한 버전 필드"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="연관된 처방",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="emr.order",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="환자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="emr.patientcache",
                    ),
                ),
                (
                    "test_master",
                    models.ForeignKey(
                        help_text="검사 마스터 정보",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lis.labtestmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "검사 결과",
                "verbose_name_plural": "검사 결과 목록",
                "db_table": "lis_lab_results",
                "ordering": ["-reported_at"],
            },
        ),
    ]
