# Generated by Django 5.2.9 on 2026-01-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labresult",
            name="test_master",
            field=models.ForeignKey(
                help_text="검사 마스터 정보",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_results",
                to="lis.labtestmaster",
            ),
        ),
    ]
