# Generated by Django 5.2.9 on 2026-01-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lis", "0002_alter_labresult_test_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtestmaster",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="labtestmaster",
            name="test_code",
            field=models.CharField(
                help_text="검사 코드 (LOINC/자체코드)", max_length=50
            ),
        ),
    ]
