# Generated by Django 5.1.6 on 2026-01-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0001_initial"),
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagingstudy",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_studies",
                to="encounters.encounter",
                verbose_name="진료",
            ),
        ),
    ]
