# Generated by Django 5.1.6 on 2026-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0002_allow_null_encounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingstudy",
            name="work_note",
            field=models.TextField(blank=True, verbose_name="작업중 특이사항"),
        ),
    ]
