# Generated by Django 5.2.9 on 2026-01-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_rolepermission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
