# Generated by Django 5.1.3 on 2025-12-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_permission_role_rolepermission_userrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "관리자"),
                    ("DOCTOR", "의사"),
                    ("NURSE", "간호사"),
                    ("RIS", "영상의학과"),
                    ("LIS", "검사실"),
                    ("PATIENT", "환자"),
                ],
                default="PATIENT",
                max_length=50,
            ),
        ),
    ]
