# Generated by Django 5.2.9 on 2026-01-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_failed_login_count_user_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
