# Generated by Django 5.2.9 on 2026-01-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_rolepermission_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolepermission",
            options={"managed": True},
        ),
    ]
