# Generated by Django 5.2.9 on 2026-01-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_rolepermission_options"),
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menus.menu"
            ),
        ),
        migrations.AlterModelTable(
            name="rolepermission",
            table="accounts_role_permissions",
        ),
    ]
