# Generated by Django 5.1.6 on 2026-01-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_role_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="부서"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workStation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="근무지"
            ),
        ),
    ]
