# Generated by Django 5.1.6 on 2026-01-09 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0001_initial"),
        ("ocs", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(
                fields=["job_role", "-created_at"], name="ocs_jobrole_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(
                fields=["is_deleted", "job_role", "-created_at"],
                name="ocs_deleted_jobrole_idx",
            ),
        ),
    ]
