# Generated by Django 5.1.6 on 2026-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0002_add_composite_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocs",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="priority가 scheduled일 때 예약된 검사 시간",
                null=True,
                verbose_name="예약일시",
            ),
        ),
    ]
