# Generated by Django 5.1.6 on 2026-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0003_add_scheduled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocs",
            name="scheduled_at",
        ),
        migrations.AlterField(
            model_name="ocs",
            name="priority",
            field=models.CharField(
                choices=[("urgent", "긴급"), ("normal", "일반")],
                default="normal",
                max_length=20,
                verbose_name="우선순위",
            ),
        ),
    ]
