# Generated by Django 5.1.6 on 2026-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0004_remove_scheduled_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocs",
            name="job_type",
            field=models.CharField(
                help_text="RIS: MRI/CT/PET/X-RAY, LIS: BLOOD/GENETIC/PROTEIN/URINE/CSF/BIOPSY, TREATMENT: SURGERY/RADIATION/CHEMOTHERAPY",
                max_length=50,
                verbose_name="작업 유형",
            ),
        ),
    ]
