# Generated by Django 5.2.9 on 2026-01-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_add_patient_alert"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="patientalert",
            new_name="patient_ale_patient_afad6f_idx",
            old_name="patient_ale_patient_7f1a3e_idx",
        ),
        migrations.RenameIndex(
            model_name="patientalert",
            new_name="patient_ale_patient_971ad1_idx",
            old_name="patient_ale_patient_6c4b2f_idx",
        ),
    ]
