# Generated by Django 5.2.9 on 2026-01-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAIL", "Login Fail"),
                    ("LOGIN_LOCKED", "Login Locked"),
                    ("LOGOUT", "Logout"),
                ],
                max_length=30,
            ),
        ),
    ]
